//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("Model", "SYS_C00693338", "AGENTS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ATRCommissions.AGENTS), "POLICES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ATRCommissions.POLICES), true)]
[assembly: EdmRelationshipAttribute("Model", "SYS_C00693337", "CLIENTS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ATRCommissions.CLIENTS), "POLICES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ATRCommissions.POLICES), true)]
[assembly: EdmRelationshipAttribute("Model", "SYS_C00693344", "POLICES", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ATRCommissions.POLICES), "PAIEMENTS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ATRCommissions.PAIEMENTS), true)]
[assembly: EdmRelationshipAttribute("Model", "SYS_C00693336", "TYPE_POLICES", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ATRCommissions.TYPE_POLICES), "POLICES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ATRCommissions.POLICES), true)]

#endregion

namespace ATRCommissions
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet Entities à l'aide de la chaîne de connexion trouvée dans la section 'Entities' du fichier de configuration d'application.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Entities.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Entities.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<AGENTS> AGENTS
        {
            get
            {
                if ((_AGENTS == null))
                {
                    _AGENTS = base.CreateObjectSet<AGENTS>("AGENTS");
                }
                return _AGENTS;
            }
        }
        private ObjectSet<AGENTS> _AGENTS;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<CLIENTS> CLIENTS
        {
            get
            {
                if ((_CLIENTS == null))
                {
                    _CLIENTS = base.CreateObjectSet<CLIENTS>("CLIENTS");
                }
                return _CLIENTS;
            }
        }
        private ObjectSet<CLIENTS> _CLIENTS;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<PAIEMENTS> PAIEMENTS
        {
            get
            {
                if ((_PAIEMENTS == null))
                {
                    _PAIEMENTS = base.CreateObjectSet<PAIEMENTS>("PAIEMENTS");
                }
                return _PAIEMENTS;
            }
        }
        private ObjectSet<PAIEMENTS> _PAIEMENTS;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<POLICES> POLICES
        {
            get
            {
                if ((_POLICES == null))
                {
                    _POLICES = base.CreateObjectSet<POLICES>("POLICES");
                }
                return _POLICES;
            }
        }
        private ObjectSet<POLICES> _POLICES;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<TYPE_POLICES> TYPE_POLICES
        {
            get
            {
                if ((_TYPE_POLICES == null))
                {
                    _TYPE_POLICES = base.CreateObjectSet<TYPE_POLICES>("TYPE_POLICES");
                }
                return _TYPE_POLICES;
            }
        }
        private ObjectSet<TYPE_POLICES> _TYPE_POLICES;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet AGENTS. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToAGENTS(AGENTS aGENTS)
        {
            base.AddObject("AGENTS", aGENTS);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet CLIENTS. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCLIENTS(CLIENTS cLIENTS)
        {
            base.AddObject("CLIENTS", cLIENTS);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet PAIEMENTS. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToPAIEMENTS(PAIEMENTS pAIEMENTS)
        {
            base.AddObject("PAIEMENTS", pAIEMENTS);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet POLICES. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToPOLICES(POLICES pOLICES)
        {
            base.AddObject("POLICES", pOLICES);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet TYPE_POLICES. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTYPE_POLICES(TYPE_POLICES tYPE_POLICES)
        {
            base.AddObject("TYPE_POLICES", tYPE_POLICES);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="AGENTS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AGENTS : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet AGENTS.
        /// </summary>
        /// <param name="aGENT_ID">Valeur initiale de la propriété AGENT_ID.</param>
        /// <param name="pROFILE">Valeur initiale de la propriété PROFILE.</param>
        /// <param name="mOT_PASSE">Valeur initiale de la propriété MOT_PASSE.</param>
        /// <param name="nOM">Valeur initiale de la propriété NOM.</param>
        /// <param name="pRENOM">Valeur initiale de la propriété PRENOM.</param>
        public static AGENTS CreateAGENTS(global::System.Decimal aGENT_ID, global::System.String pROFILE, global::System.String mOT_PASSE, global::System.String nOM, global::System.String pRENOM)
        {
            AGENTS aGENTS = new AGENTS();
            aGENTS.AGENT_ID = aGENT_ID;
            aGENTS.PROFILE = pROFILE;
            aGENTS.MOT_PASSE = mOT_PASSE;
            aGENTS.NOM = nOM;
            aGENTS.PRENOM = pRENOM;
            return aGENTS;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AGENT_ID
        {
            get
            {
                return _AGENT_ID;
            }
            set
            {
                if (_AGENT_ID != value)
                {
                    OnAGENT_IDChanging(value);
                    ReportPropertyChanging("AGENT_ID");
                    _AGENT_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AGENT_ID");
                    OnAGENT_IDChanged();
                }
            }
        }
        private global::System.Decimal _AGENT_ID;
        partial void OnAGENT_IDChanging(global::System.Decimal value);
        partial void OnAGENT_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PROFILE
        {
            get
            {
                return _PROFILE;
            }
            set
            {
                OnPROFILEChanging(value);
                ReportPropertyChanging("PROFILE");
                _PROFILE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PROFILE");
                OnPROFILEChanged();
            }
        }
        private global::System.String _PROFILE;
        partial void OnPROFILEChanging(global::System.String value);
        partial void OnPROFILEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MOT_PASSE
        {
            get
            {
                return _MOT_PASSE;
            }
            set
            {
                OnMOT_PASSEChanging(value);
                ReportPropertyChanging("MOT_PASSE");
                _MOT_PASSE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MOT_PASSE");
                OnMOT_PASSEChanged();
            }
        }
        private global::System.String _MOT_PASSE;
        partial void OnMOT_PASSEChanging(global::System.String value);
        partial void OnMOT_PASSEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOM
        {
            get
            {
                return _NOM;
            }
            set
            {
                OnNOMChanging(value);
                ReportPropertyChanging("NOM");
                _NOM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOM");
                OnNOMChanged();
            }
        }
        private global::System.String _NOM;
        partial void OnNOMChanging(global::System.String value);
        partial void OnNOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PRENOM
        {
            get
            {
                return _PRENOM;
            }
            set
            {
                OnPRENOMChanging(value);
                ReportPropertyChanging("PRENOM");
                _PRENOM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PRENOM");
                OnPRENOMChanged();
            }
        }
        private global::System.String _PRENOM;
        partial void OnPRENOMChanging(global::System.String value);
        partial void OnPRENOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADRESSE
        {
            get
            {
                return _ADRESSE;
            }
            set
            {
                OnADRESSEChanging(value);
                ReportPropertyChanging("ADRESSE");
                _ADRESSE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADRESSE");
                OnADRESSEChanged();
            }
        }
        private global::System.String _ADRESSE;
        partial void OnADRESSEChanging(global::System.String value);
        partial void OnADRESSEChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "SYS_C00693338", "POLICES")]
        public EntityCollection<POLICES> POLICES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<POLICES>("Model.SYS_C00693338", "POLICES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<POLICES>("Model.SYS_C00693338", "POLICES", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CLIENTS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CLIENTS : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet CLIENTS.
        /// </summary>
        /// <param name="cLIENT_ID">Valeur initiale de la propriété CLIENT_ID.</param>
        /// <param name="nOM">Valeur initiale de la propriété NOM.</param>
        /// <param name="pRENOM">Valeur initiale de la propriété PRENOM.</param>
        public static CLIENTS CreateCLIENTS(global::System.Decimal cLIENT_ID, global::System.String nOM, global::System.String pRENOM)
        {
            CLIENTS cLIENTS = new CLIENTS();
            cLIENTS.CLIENT_ID = cLIENT_ID;
            cLIENTS.NOM = nOM;
            cLIENTS.PRENOM = pRENOM;
            return cLIENTS;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CLIENT_ID
        {
            get
            {
                return _CLIENT_ID;
            }
            set
            {
                if (_CLIENT_ID != value)
                {
                    OnCLIENT_IDChanging(value);
                    ReportPropertyChanging("CLIENT_ID");
                    _CLIENT_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CLIENT_ID");
                    OnCLIENT_IDChanged();
                }
            }
        }
        private global::System.Decimal _CLIENT_ID;
        partial void OnCLIENT_IDChanging(global::System.Decimal value);
        partial void OnCLIENT_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOM
        {
            get
            {
                return _NOM;
            }
            set
            {
                OnNOMChanging(value);
                ReportPropertyChanging("NOM");
                _NOM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOM");
                OnNOMChanged();
            }
        }
        private global::System.String _NOM;
        partial void OnNOMChanging(global::System.String value);
        partial void OnNOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PRENOM
        {
            get
            {
                return _PRENOM;
            }
            set
            {
                OnPRENOMChanging(value);
                ReportPropertyChanging("PRENOM");
                _PRENOM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PRENOM");
                OnPRENOMChanged();
            }
        }
        private global::System.String _PRENOM;
        partial void OnPRENOMChanging(global::System.String value);
        partial void OnPRENOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADRESSE
        {
            get
            {
                return _ADRESSE;
            }
            set
            {
                OnADRESSEChanging(value);
                ReportPropertyChanging("ADRESSE");
                _ADRESSE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADRESSE");
                OnADRESSEChanged();
            }
        }
        private global::System.String _ADRESSE;
        partial void OnADRESSEChanging(global::System.String value);
        partial void OnADRESSEChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "SYS_C00693337", "POLICES")]
        public EntityCollection<POLICES> POLICES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<POLICES>("Model.SYS_C00693337", "POLICES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<POLICES>("Model.SYS_C00693337", "POLICES", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="PAIEMENTS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PAIEMENTS : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet PAIEMENTS.
        /// </summary>
        /// <param name="pAIEMENT_ID">Valeur initiale de la propriété PAIEMENT_ID.</param>
        /// <param name="tYPE_PAIEMENT">Valeur initiale de la propriété TYPE_PAIEMENT.</param>
        /// <param name="nUM_CHEQUE">Valeur initiale de la propriété NUM_CHEQUE.</param>
        /// <param name="dATE_PAIEMENT">Valeur initiale de la propriété DATE_PAIEMENT.</param>
        /// <param name="pOLICE_ID">Valeur initiale de la propriété POLICE_ID.</param>
        public static PAIEMENTS CreatePAIEMENTS(global::System.Decimal pAIEMENT_ID, global::System.String tYPE_PAIEMENT, global::System.String nUM_CHEQUE, global::System.DateTime dATE_PAIEMENT, global::System.Decimal pOLICE_ID)
        {
            PAIEMENTS pAIEMENTS = new PAIEMENTS();
            pAIEMENTS.PAIEMENT_ID = pAIEMENT_ID;
            pAIEMENTS.TYPE_PAIEMENT = tYPE_PAIEMENT;
            pAIEMENTS.NUM_CHEQUE = nUM_CHEQUE;
            pAIEMENTS.DATE_PAIEMENT = dATE_PAIEMENT;
            pAIEMENTS.POLICE_ID = pOLICE_ID;
            return pAIEMENTS;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PAIEMENT_ID
        {
            get
            {
                return _PAIEMENT_ID;
            }
            set
            {
                if (_PAIEMENT_ID != value)
                {
                    OnPAIEMENT_IDChanging(value);
                    ReportPropertyChanging("PAIEMENT_ID");
                    _PAIEMENT_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PAIEMENT_ID");
                    OnPAIEMENT_IDChanged();
                }
            }
        }
        private global::System.Decimal _PAIEMENT_ID;
        partial void OnPAIEMENT_IDChanging(global::System.Decimal value);
        partial void OnPAIEMENT_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TYPE_PAIEMENT
        {
            get
            {
                return _TYPE_PAIEMENT;
            }
            set
            {
                OnTYPE_PAIEMENTChanging(value);
                ReportPropertyChanging("TYPE_PAIEMENT");
                _TYPE_PAIEMENT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TYPE_PAIEMENT");
                OnTYPE_PAIEMENTChanged();
            }
        }
        private global::System.String _TYPE_PAIEMENT;
        partial void OnTYPE_PAIEMENTChanging(global::System.String value);
        partial void OnTYPE_PAIEMENTChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NUM_CHEQUE
        {
            get
            {
                return _NUM_CHEQUE;
            }
            set
            {
                OnNUM_CHEQUEChanging(value);
                ReportPropertyChanging("NUM_CHEQUE");
                _NUM_CHEQUE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NUM_CHEQUE");
                OnNUM_CHEQUEChanged();
            }
        }
        private global::System.String _NUM_CHEQUE;
        partial void OnNUM_CHEQUEChanging(global::System.String value);
        partial void OnNUM_CHEQUEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATE_PAIEMENT
        {
            get
            {
                return _DATE_PAIEMENT;
            }
            set
            {
                OnDATE_PAIEMENTChanging(value);
                ReportPropertyChanging("DATE_PAIEMENT");
                _DATE_PAIEMENT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_PAIEMENT");
                OnDATE_PAIEMENTChanged();
            }
        }
        private global::System.DateTime _DATE_PAIEMENT;
        partial void OnDATE_PAIEMENTChanging(global::System.DateTime value);
        partial void OnDATE_PAIEMENTChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTANT_PAIEMENT
        {
            get
            {
                return _MONTANT_PAIEMENT;
            }
            set
            {
                OnMONTANT_PAIEMENTChanging(value);
                ReportPropertyChanging("MONTANT_PAIEMENT");
                _MONTANT_PAIEMENT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTANT_PAIEMENT");
                OnMONTANT_PAIEMENTChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTANT_PAIEMENT;
        partial void OnMONTANT_PAIEMENTChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTANT_PAIEMENTChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal POLICE_ID
        {
            get
            {
                return _POLICE_ID;
            }
            set
            {
                OnPOLICE_IDChanging(value);
                ReportPropertyChanging("POLICE_ID");
                _POLICE_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("POLICE_ID");
                OnPOLICE_IDChanged();
            }
        }
        private global::System.Decimal _POLICE_ID;
        partial void OnPOLICE_IDChanging(global::System.Decimal value);
        partial void OnPOLICE_IDChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "SYS_C00693344", "POLICES")]
        public POLICES POLICES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<POLICES>("Model.SYS_C00693344", "POLICES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<POLICES>("Model.SYS_C00693344", "POLICES").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<POLICES> POLICESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<POLICES>("Model.SYS_C00693344", "POLICES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<POLICES>("Model.SYS_C00693344", "POLICES", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="POLICES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class POLICES : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet POLICES.
        /// </summary>
        /// <param name="pOLICE_ID">Valeur initiale de la propriété POLICE_ID.</param>
        /// <param name="eTAT">Valeur initiale de la propriété ETAT.</param>
        /// <param name="fEQUENCE_PAIEMENT_CLIENT">Valeur initiale de la propriété FEQUENCE_PAIEMENT_CLIENT.</param>
        /// <param name="tYPE_ID">Valeur initiale de la propriété TYPE_ID.</param>
        /// <param name="cLIENT_ID">Valeur initiale de la propriété CLIENT_ID.</param>
        /// <param name="aGENT_ID">Valeur initiale de la propriété AGENT_ID.</param>
        public static POLICES CreatePOLICES(global::System.Decimal pOLICE_ID, global::System.String eTAT, global::System.String fEQUENCE_PAIEMENT_CLIENT, global::System.Decimal tYPE_ID, global::System.Decimal cLIENT_ID, global::System.Decimal aGENT_ID)
        {
            POLICES pOLICES = new POLICES();
            pOLICES.POLICE_ID = pOLICE_ID;
            pOLICES.ETAT = eTAT;
            pOLICES.FEQUENCE_PAIEMENT_CLIENT = fEQUENCE_PAIEMENT_CLIENT;
            pOLICES.TYPE_ID = tYPE_ID;
            pOLICES.CLIENT_ID = cLIENT_ID;
            pOLICES.AGENT_ID = aGENT_ID;
            return pOLICES;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal POLICE_ID
        {
            get
            {
                return _POLICE_ID;
            }
            set
            {
                if (_POLICE_ID != value)
                {
                    OnPOLICE_IDChanging(value);
                    ReportPropertyChanging("POLICE_ID");
                    _POLICE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("POLICE_ID");
                    OnPOLICE_IDChanged();
                }
            }
        }
        private global::System.Decimal _POLICE_ID;
        partial void OnPOLICE_IDChanging(global::System.Decimal value);
        partial void OnPOLICE_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ETAT
        {
            get
            {
                return _ETAT;
            }
            set
            {
                OnETATChanging(value);
                ReportPropertyChanging("ETAT");
                _ETAT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ETAT");
                OnETATChanged();
            }
        }
        private global::System.String _ETAT;
        partial void OnETATChanging(global::System.String value);
        partial void OnETATChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE_DEBUT
        {
            get
            {
                return _DATE_DEBUT;
            }
            set
            {
                OnDATE_DEBUTChanging(value);
                ReportPropertyChanging("DATE_DEBUT");
                _DATE_DEBUT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_DEBUT");
                OnDATE_DEBUTChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE_DEBUT;
        partial void OnDATE_DEBUTChanging(Nullable<global::System.DateTime> value);
        partial void OnDATE_DEBUTChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE_FIN
        {
            get
            {
                return _DATE_FIN;
            }
            set
            {
                OnDATE_FINChanging(value);
                ReportPropertyChanging("DATE_FIN");
                _DATE_FIN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_FIN");
                OnDATE_FINChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE_FIN;
        partial void OnDATE_FINChanging(Nullable<global::System.DateTime> value);
        partial void OnDATE_FINChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE_ACHAT
        {
            get
            {
                return _DATE_ACHAT;
            }
            set
            {
                OnDATE_ACHATChanging(value);
                ReportPropertyChanging("DATE_ACHAT");
                _DATE_ACHAT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_ACHAT");
                OnDATE_ACHATChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE_ACHAT;
        partial void OnDATE_ACHATChanging(Nullable<global::System.DateTime> value);
        partial void OnDATE_ACHATChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE_ANNULATION
        {
            get
            {
                return _DATE_ANNULATION;
            }
            set
            {
                OnDATE_ANNULATIONChanging(value);
                ReportPropertyChanging("DATE_ANNULATION");
                _DATE_ANNULATION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_ANNULATION");
                OnDATE_ANNULATIONChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE_ANNULATION;
        partial void OnDATE_ANNULATIONChanging(Nullable<global::System.DateTime> value);
        partial void OnDATE_ANNULATIONChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTANT_COM
        {
            get
            {
                return _MONTANT_COM;
            }
            set
            {
                OnMONTANT_COMChanging(value);
                ReportPropertyChanging("MONTANT_COM");
                _MONTANT_COM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTANT_COM");
                OnMONTANT_COMChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTANT_COM;
        partial void OnMONTANT_COMChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTANT_COMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FEQUENCE_PAIEMENT_CLIENT
        {
            get
            {
                return _FEQUENCE_PAIEMENT_CLIENT;
            }
            set
            {
                OnFEQUENCE_PAIEMENT_CLIENTChanging(value);
                ReportPropertyChanging("FEQUENCE_PAIEMENT_CLIENT");
                _FEQUENCE_PAIEMENT_CLIENT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FEQUENCE_PAIEMENT_CLIENT");
                OnFEQUENCE_PAIEMENT_CLIENTChanged();
            }
        }
        private global::System.String _FEQUENCE_PAIEMENT_CLIENT;
        partial void OnFEQUENCE_PAIEMENT_CLIENTChanging(global::System.String value);
        partial void OnFEQUENCE_PAIEMENT_CLIENTChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTANT_PAIEMENT_CLIENT
        {
            get
            {
                return _MONTANT_PAIEMENT_CLIENT;
            }
            set
            {
                OnMONTANT_PAIEMENT_CLIENTChanging(value);
                ReportPropertyChanging("MONTANT_PAIEMENT_CLIENT");
                _MONTANT_PAIEMENT_CLIENT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTANT_PAIEMENT_CLIENT");
                OnMONTANT_PAIEMENT_CLIENTChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTANT_PAIEMENT_CLIENT;
        partial void OnMONTANT_PAIEMENT_CLIENTChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTANT_PAIEMENT_CLIENTChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TYPE_ID
        {
            get
            {
                return _TYPE_ID;
            }
            set
            {
                OnTYPE_IDChanging(value);
                ReportPropertyChanging("TYPE_ID");
                _TYPE_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TYPE_ID");
                OnTYPE_IDChanged();
            }
        }
        private global::System.Decimal _TYPE_ID;
        partial void OnTYPE_IDChanging(global::System.Decimal value);
        partial void OnTYPE_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CLIENT_ID
        {
            get
            {
                return _CLIENT_ID;
            }
            set
            {
                OnCLIENT_IDChanging(value);
                ReportPropertyChanging("CLIENT_ID");
                _CLIENT_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLIENT_ID");
                OnCLIENT_IDChanged();
            }
        }
        private global::System.Decimal _CLIENT_ID;
        partial void OnCLIENT_IDChanging(global::System.Decimal value);
        partial void OnCLIENT_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AGENT_ID
        {
            get
            {
                return _AGENT_ID;
            }
            set
            {
                OnAGENT_IDChanging(value);
                ReportPropertyChanging("AGENT_ID");
                _AGENT_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AGENT_ID");
                OnAGENT_IDChanged();
            }
        }
        private global::System.Decimal _AGENT_ID;
        partial void OnAGENT_IDChanging(global::System.Decimal value);
        partial void OnAGENT_IDChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "SYS_C00693338", "AGENTS")]
        public AGENTS AGENTS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AGENTS>("Model.SYS_C00693338", "AGENTS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AGENTS>("Model.SYS_C00693338", "AGENTS").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AGENTS> AGENTSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AGENTS>("Model.SYS_C00693338", "AGENTS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AGENTS>("Model.SYS_C00693338", "AGENTS", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "SYS_C00693337", "CLIENTS")]
        public CLIENTS CLIENTS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTS>("Model.SYS_C00693337", "CLIENTS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTS>("Model.SYS_C00693337", "CLIENTS").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CLIENTS> CLIENTSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTS>("Model.SYS_C00693337", "CLIENTS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CLIENTS>("Model.SYS_C00693337", "CLIENTS", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "SYS_C00693344", "PAIEMENTS")]
        public EntityCollection<PAIEMENTS> PAIEMENTS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PAIEMENTS>("Model.SYS_C00693344", "PAIEMENTS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PAIEMENTS>("Model.SYS_C00693344", "PAIEMENTS", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "SYS_C00693336", "TYPE_POLICES")]
        public TYPE_POLICES TYPE_POLICES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TYPE_POLICES>("Model.SYS_C00693336", "TYPE_POLICES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TYPE_POLICES>("Model.SYS_C00693336", "TYPE_POLICES").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TYPE_POLICES> TYPE_POLICESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TYPE_POLICES>("Model.SYS_C00693336", "TYPE_POLICES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TYPE_POLICES>("Model.SYS_C00693336", "TYPE_POLICES", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="TYPE_POLICES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TYPE_POLICES : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet TYPE_POLICES.
        /// </summary>
        /// <param name="tYPE_ID">Valeur initiale de la propriété TYPE_ID.</param>
        /// <param name="nOM_POLICE">Valeur initiale de la propriété NOM_POLICE.</param>
        public static TYPE_POLICES CreateTYPE_POLICES(global::System.Decimal tYPE_ID, global::System.String nOM_POLICE)
        {
            TYPE_POLICES tYPE_POLICES = new TYPE_POLICES();
            tYPE_POLICES.TYPE_ID = tYPE_ID;
            tYPE_POLICES.NOM_POLICE = nOM_POLICE;
            return tYPE_POLICES;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TYPE_ID
        {
            get
            {
                return _TYPE_ID;
            }
            set
            {
                if (_TYPE_ID != value)
                {
                    OnTYPE_IDChanging(value);
                    ReportPropertyChanging("TYPE_ID");
                    _TYPE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TYPE_ID");
                    OnTYPE_IDChanged();
                }
            }
        }
        private global::System.Decimal _TYPE_ID;
        partial void OnTYPE_IDChanging(global::System.Decimal value);
        partial void OnTYPE_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOM_POLICE
        {
            get
            {
                return _NOM_POLICE;
            }
            set
            {
                OnNOM_POLICEChanging(value);
                ReportPropertyChanging("NOM_POLICE");
                _NOM_POLICE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOM_POLICE");
                OnNOM_POLICEChanged();
            }
        }
        private global::System.String _NOM_POLICE;
        partial void OnNOM_POLICEChanging(global::System.String value);
        partial void OnNOM_POLICEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> POURCENTAGE_COM
        {
            get
            {
                return _POURCENTAGE_COM;
            }
            set
            {
                OnPOURCENTAGE_COMChanging(value);
                ReportPropertyChanging("POURCENTAGE_COM");
                _POURCENTAGE_COM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("POURCENTAGE_COM");
                OnPOURCENTAGE_COMChanged();
            }
        }
        private Nullable<global::System.Decimal> _POURCENTAGE_COM;
        partial void OnPOURCENTAGE_COMChanging(Nullable<global::System.Decimal> value);
        partial void OnPOURCENTAGE_COMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PRIX
        {
            get
            {
                return _PRIX;
            }
            set
            {
                OnPRIXChanging(value);
                ReportPropertyChanging("PRIX");
                _PRIX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRIX");
                OnPRIXChanged();
            }
        }
        private Nullable<global::System.Decimal> _PRIX;
        partial void OnPRIXChanging(Nullable<global::System.Decimal> value);
        partial void OnPRIXChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "SYS_C00693336", "POLICES")]
        public EntityCollection<POLICES> POLICES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<POLICES>("Model.SYS_C00693336", "POLICES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<POLICES>("Model.SYS_C00693336", "POLICES", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
